### ISSUE TITLE
Debug draw shape wrong draw

### ISSUE THREAD

**Issue by caxapexac** [irlanrobson/bounce#12]
shape.cpp, line 42

```cpp
b3Vec3 p1 = xf * capsule->m_vertex1;
b3Vec3 p2 = xf * capsule->m_vertex2;
draw->DrawPoint(p1, scalar(4), color);
draw->DrawPoint(p2, scalar(4), color);
draw->DrawSegment(p1, p2, color);
```
Should be changed to
```cpp
b3Vec3 c1 = xf * capsule->m_vertex1;
b3Vec3 c2 = xf * capsule->m_vertex2;
draw->DrawCapsule(c1, c2, capsule->m_radius, color);
```

Also API of draw:
```cpp
virtual void DrawSolidCapsule(const b3Quat& rotation, const b3Vec3& p1, const b3Vec3& p2, scalar radius, const b3Color& color, bool depthEnabled = true) = 0;
```
rotation is found implicitly from p1 and p2 but rotation is passed as argument (DrawCapsule doesn't have this mistake)

**Comment by irlanrobson** [comment]
Oh I'm not sure it is a good idea because we really want to see the capsule segment (geometry) for debugging. Collision detection is performed using the segment.

As for the rotation that's because I draw a capsule using a cylinder and two spheres at the capsule vertices and the sphere draw function needs a rotation. I prefer passing a well defined rotation instead of finding it because this is faster.

**Comment by caxapexac** [comment]
> Oh I'm not sure it is a good idea because we really want to see the capsule segment (geometry) for debugging. Collision detection is performed using the segment.

But we can't see the width of the capsule because you draw it using constant radius 4

**Comment by irlanrobson** [comment]
You should have a look more closely and try to understand the code before opening an issue. That's the size of a point, not the radius of a sphere. There's no problem there. If you want to see the capsule mesh implement your own debug draw.
