### ISSUE TITLE
GetTransform vs GetPosition/Orientation

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#13]
Does it matter which is used for updating a visual representation of a body?

I'm having some trouble with jittery movements (currently using GetPosition/GetOrientation) and before I write some code to convert the Mat3 -> Quaternion returned by GetTransform I just wanted to know if that makes any difference?

**Comment by irlanrobson** [comment]
Yes, it does! Currently, you would use GetTransform because GetPosition it's returning the world center of mass of the body without taking the local center of mass into account. This is wrong and it should return the translation part of the transform. Sorry! I'll fix it now then close this issue. 

Just for clarification. Theoretically, the transform is a 4x4 matrix. It's used for performing affine transformations on 4x1 vectors in affine space. If it transforms points then the last row vector in the matrix is zero, and the last element in the 4x1 vector is 1 and is preserved after the transformation. Because of this, practically a transformation is represented by a 3x4 matrix assuming the last row vector is zero, and a point by a 3x1 vector assuming a last element in this vector exists and is equal 1. Thus, the product of a 3x4 matrix and a 3x1 vector is defined.

**Comment by Kazade** [comment]
Thanks! Yeah that all makes sense - unfortunately it doesn't fix my jittering issue so my issue must lie elsewhere in my code :(

**Comment by RandyGaul** [comment]
Jittering is probably the different frequencies of updating between your graphics and physics. If physics is updated for example 3 times a second, but graphics renders 10 times a second, then some displayed frames will be still for 3 frames, and other times for 4 frames. The eye can see this difference and movement will look jittery.

The solution to this problem is to store extra information along with transforms, enough to interpolate between the N-1 and Nth physics positions (N is current frame, N-1 is previous frame). This introduces 1 frame of steady-state lag, but that's OK. The interpolation will smooth out movement between physics states, letting graphics render at any frequency it wants, decoupled from the physics tick-rate.

**Comment by irlanrobson** [comment]
The changes have been made. Now GetWorldCenter/LocalCenter returns the world and local center of mass and GetPosition returns the position of the world body origin.

**Comment by irlanrobson** [comment]
Is the convex cache enabled?

**Comment by irlanrobson** [comment]
You can enable it by declaring  

extern u32 b3_convexCache

and defining it to true. However, it's enabled by default.

Last month this was defined to be an option for testing. If it's disabled and the position solver then it has an important consequence for hull vs. hull contacts and may lead to jittering. Play with the InitialOverlap test in the testbed.

**Comment by Kazade** [comment]
At the moment I don't even have any colliders, just a rigid body. It's so weird, every movement (rotation or linear) seems to "judder" the faster the object moves, the worse the judder.

I just tried dropping from 1.0 / 60 to 1.0 / 30 and now the judder seems to happen even faster... I'm sure it's just something I'm doing. It's annoyingly difficult to track down as I've integrated bounce into my game engine (which is really large) so it could be anything really.

**Comment by RandyGaul** [comment]
If you aren't render at the same frequency as the physics, and are not doing the interpolation solution I described above, there will always be that visual jitter.

**Comment by Kazade** [comment]
Yeah i have a fixed timestep accumulator and interpolation, I'm sure it's something to do with my engine. I'll let you know when i figure it out :) thanks for the help!

**Comment by RandyGaul** [comment]
Try logging the interpolant along with frame times to try and validate all the figures are correct :)

**Comment by RandyGaul** [comment]
In the above example the interpolant would be:

    float t = render_time - logic_time;
    ASSERT( t >= 0 && t <= 1.0f );
    RenderGame( t );

**Comment by Kazade** [comment]
I've done more investigating, I'm still no closer to figuring it out. Now I have two demo apps:

1. Spawns random boxes, they fall
2. Has a ship that's controllable by the keyboard

The first one seems to work fine, I don't see any jitter there. The second one shows this "juddering" as if the ship is only moving a small number of times a second (considerably less than 60). 

Let me explain my set-up, perhaps you'll have some insight into what I'm doing wrong here...

My engine mimics Unity in that it has 3 update methods for each controller: `fixed_update`, `update` and `late_update`. They are run in that order in the game loop (but `fixed_update` could run zero or more times depending on the accumulator). I'm currently applying forces in `fixed_update` if the key is pressed, it's also during the fixed update loop when the simulation is Stepped (so effectively it's apply force -> step -> apply force ->step).

Does that sound correct? Or should I apply forces only in update and multiply by the frame time?

**Comment by irlanrobson** [comment]
Yes, that does sound correct. 

Bounce assumes a constant time step. Yes, varying time steps it's common in some applications. I need to make the proper changes for this to work. It also assumes the force is constant during the time step.

**Comment by Kazade** [comment]
Right, so it turns out my interpolation is broken, but, that's not the whole story. Without interpolation the steps of movement are far greater than I'd expect at 1/60, but now I'm questioning whether my camera is the cause of all this. If the camera is following an old position then it might explain the problem and my other sample doesn't use a follow cam. This is almost certainly not a Bounce issue though so I'll close this ticket, but I'll post back anyway.

**Comment by irlanrobson** [comment]
Try setting up the simplest scene and a fixed camera. Then analyse or step through this to identify the problem.
