### ISSUE TITLE
b3StaticTree::BuildTree seems slow

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#20]
Hi!

I have a mesh which has 1181 triangles, and 4096 vertices (a 64x64 heightmap) and I'm using it to generate a static mesh collider. Once the tree is built Bounce copes really well with it (the framerate stays very high) but BuildTree itself can take a couple of minutes.

I haven't done any serious profiling yet, but pausing the debugger while I'm waiting for it to build drops me around this line: https://github.com/irlanrobson/bounce/blob/master/src/bounce/collision/trees/static_tree.cpp#L137

I'm wondering if a combination of `std::partition` (to find all elements where `center[splitAxis] < splitPos`) combined with `std::nth_element` (to find the last element sorted by the predicate) might be quicker? If I find time I'll play around to see if that helps.

My only other question is, does the tree have to be rebuilt if the object is relocated? I'm considering disk caching the resulting tree for a mesh for faster loading if that's the case.

**Comment by Kazade** [comment]
Nah my idea doesn't work as the whole range appears to need sorting

**Comment by irlanrobson** [comment]
b3Mesh is a resource. 
For each b3Mesh object there is a unique b3StaticTree object.

**Comment by irlanrobson** [comment]
Try increasing the capacity of stack at

https://github.com/irlanrobson/bounce/blob/master/src/bounce/collision/trees/static_tree.cpp#L87

The `BuildTree` routine implements a top-down AABB tree construction and splits the current subset at the median. This algorithm is one of the simplest in the collision detection field. Since the insertion method is off-line, a small part of time has been spent in developing this builder or more robust tree builders with better algorithmic performance. There are more important things to work on before.

**Comment by irlanrobson** [comment]
So yeah, you should cache b3Mesh and b3StaticTree objects.

**Comment by rosemick3d** [comment]
Second this issue. Building static BVHs with large triangles is tough sometimes. Although not a problem because we cook meshes off-line and also use mesh simplificators to get clean collision manifolds. 

Increasing the stack size to something like 2048 for a lot of triangles increased performance ~20% for me.

**Comment by irlanrobson** [comment]
Static tree construction has been improved a little. It doesn't use std::sort anymore. I also changed the recursive calls to run through the call stack instead of the user stack. In practice it doesn't matter much since these steps should be pre-processes.

Kazade, do these changes fix this issue? I cannot promise to improve the algorithmic performance of this tree builder soon.

**Comment by rosemick3d** [comment]
I just gave it a test and it works fine both in debug release builds. Thanks.

**Comment by irlanrobson** [comment]
Thanks Rosemick. 

Some dense meshes have been compiled and performance was improved after the last optimization. Specially in the debug builds. I know what std::sort implements (Quicksort) but I don't know how it is implemented. For the moment it's better maintain my own routines that requires no additional memory for sorting. The issue will be closed but feel free to reopen this issue if anyone finds a problem.
