### ISSUE TITLE
How can I move the center of mass?

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#33]
Just a quick question really.  I'm following a tutorial video to implement a raycast vehicle, and to help prevent the car from rolling over, in the tutorial they say to move the center of mass of the vehicle downward: https://youtu.be/LG1CtlFRmpU?t=310

How an I achieve this with Bounce? I see there is a local center on the body but there doesn't seem to be a way to manipulate it.

Thanks!

**Comment by Kazade** [comment]
Perfect, thank you!

**Comment by Kazade** [comment]
Hi, am I doing this right?

```
    b3MassData data;
    body->GetMassData(&data);
    /// ... manipulate data.center here ...
    body->SetMassData(&data);
```

When I try moving the center of mass like this, the object stops colliding with things...

**Comment by irlanrobson** [comment]
Yes. If you could provide more details on how this problem has happened it would help me find the bug.

**Comment by RandyGaul** [comment]
Just a guess, but does the GetMassData adjust the broadphase proxy if the position was adjusted? Also, does it handle teleporting a large distance (i.e. do not create a very stretched AABB in the DBVH)?

**Comment by irlanrobson** [comment]
> Hi, am I doing this right?

Just a correction and a few notes to help the users of this library understand the inertia. The inertia tensor retrieved using GetMassData is about the body local center of mass, not the body origin. Initially, the inertia was shifted using the formula

I_c = I_o - m * S(center)

The S in this equation is a special matrix called the Steiner matrix. As you can see the inertia about the local center of mass is small.

Remember that the body origin is the position where all shapes are relative to the body.

The body local center of mass is the mass-weighted average local center of mass of all shapes that make-up the body.

We would need to set the inertia inside `b3MassData` to the inertia about the body origin, since it will be shifted to the given local center of mass inside `b3MassData`.

**Comment by irlanrobson** [comment]
I can modify the function `GetMassData `to return the inertia about the body origin, since we have a typical situation of just altering the center of mases.

**Comment by irlanrobson** [comment]
Changing the function breaks consistency, since the local center of mass is returned too. Users will have to compute the inertia about the body origin. Of course that means rewriting the equation above:

I_c = I_o - m * S(center) 

to

I_o = I_c + m * S(center)

**Comment by irlanrobson** [comment]
Of course that doesn't fix the problem. I will have to sit down and localize where the bug is.

**Comment by irlanrobson** [comment]
@RandyGaul 

> Just a guess, but does the GetMassData adjust the broadphase proxy if the position was adjusted?

No, it does not. This happens when the transform of the body is changed by an user. Currently, it would be adjusted at the end of the next step.

Also, does it handle teleporting a large distance (i.e. do not create a very stretched AABB in the DBVH)?

No, it doesn't handle this case. Would this be an optimization for not rebuilding the tree? Note that there is no CCD currently.

As for Kazade's issue. I think the issue is that we are moving the inertia to the local center of mass twice. The inertia at the original center of mass is the smallest. This would give an inertia with negative diagonal entries. A badly defined inertia makes the contact unsolvable.

SetMassData expects an inertia about the local body origin as it shifts it to the given local center of mass inside the function. I think we would need to move the inertia about the body origin away to a shifted origin first by the displacement vector from the old center of mass to the new center of mass using the formula I += m * d^2 before passing it to SetMassData. This would guarante a positive inertia.

**Comment by Kazade** [comment]
Thanks! I'll try those things when I get time and post back.

**Comment by irlanrobson** [comment]
Hi @Kazade 

Now there is some code that makes the hull inertia computation more robust. In particular, it can help to reduce floating-point round-off errors the hull is far away from its parent body. So some asserts are not hit in that case.

There is a new collision shape called b3QHull. It allows the users to create convex hulls from a array of points quickly (that's the reason of the prefix 'Q'). 

Example:

```
// Creates an array of points
b3Vec3* points = nullptr;
u32 pointCount = CreatePoints(points);

// Create the convex hull from the point array
b3QHull hull;
hull.Set(points, pointCount);

// Plug the hull in a b3HullShape
b3HullShape hullShape;
hullShape.m_hull = &hull;

//
b3ShapeDef sd;
// ...

// Create the body as you do and the shape as below and you are done.
b3HullShape* bodyHullShape = static_cast<b3HullShape*>( body->CreateShape(sd) );

```
The implementation of the convex hull algorithm that we use (which is Quickhull) is not very robust. It might have troubles building the convex hull for a complex point cloud. Therefore, I recomend users to use b3QHull for the creation of simple convex hulls of shapes like cylinders, cones, rounded tables, simple cars, walls, etc. This is also a good limitation for obtaining good performance of the collision system.

After these changes perhaps you can accomplish the tasks that you were doing recently at smaller degree of difficulty.
