### ISSUE TITLE
Bounce vs Bounce Lite

### ISSUE THREAD

**Issue by Josid88** [irlanrobson/bounce#47]
Hi, I'm looking for a small 3d physics engine for a videogame, I came here from qu3e engine because it lacks of some shapes(triangles, cylinders, spheres) and constraints.

Do you have a list of the main differences between Bounce and Bouce Lite.

Compared to Bullet physics, could you please tell me which do you think is better(Bounce vs Bullet) in:
Performance.
Easy Coding.
Less memory.
Smaller binaries

I only need a physics engine to handle explosions(rigid body bouncing), some complex raycasting, and ragdolls.

Thanks in advance.

**Comment by irlanrobson** [comment]
> Hi, I'm looking for a small 3d physics engine for a videogame, I came here from qu3e engine because it lacks of some shapes(triangles, cylinders, spheres) and constraints.

Hi there. 

One would use qu3e in production code if the product he is tinking is one whose physical environment and objects are oriented boxes. qu3e is very fast and simple/easy to use.

If you need an engine similar to qu3e but with more features you have come to the right place.

> Do you have a list of the main differences between Bounce and Bouce Lite.

The feature list of both engines are in their github project page. You clearly see the differences between those in there. 

Basically Bounce Lite only supports hulls. Bounce supports more shapes: spheres, capsules, convex hulls and triangle meshes. It also supports joints.

> Compared to Bullet physics, could you please tell me which do you think is better(Bounce vs Bullet) in:
> Performance.
> Easy Coding.
> Less memory.
> Smaller binaries
> 

Performance: I haven't run a benchmark. You would have to test both to come up with a conclusion.

Easy Coding: In my opinion Bounce is better because it is more consistent than Bullet. Bullet is mostly maintained by collaborators all around the globe.

Less memory: I don't know. Probably Bounce utilizes memory better than Bullet does. You can change some memory settings inside the allocator source code.

Smaller Binaries: Not sure. You would have to test and compare as well.

> I only need a physics engine to handle explosions(rigid body bouncing), some complex raycasting, and ragdolls.

Bounce supports varying restitution, ray casting and AABB queries. You can build up ragdolls using conical joints. Those are supported too. See the test Ragdoll in the Testbed.

Good luck with your game!
