### ISSUE TITLE
Multithreaded Pipeline Potential

### ISSUE THREAD

**Issue by ForgeMistress** [irlanrobson/bounce#49]
I am evaluating physics engines for a project and after reviewing your code and testing out some of your demos, I really like what I see! However I am noticing that there is no multithreaded CPU pipeline as of yet. There is simply the b3World running on the calling thread. I was wondering if you had given any thought into implementing a multi-threaded version of your algorithm with a library like cpp-taskflow.

**Comment by irlanrobson** [comment]
Hi ForgeMistress,

I'm glad you liked Bounce.

No, I hadn't given any though of multi-threading in Bounce. There is absolutely no multi-threaded code here. Ideally you would have one b3World per thread. All the code inside b3World is single-threaded. 

If you really need a multi-threaded physics environment I suggest you to study other alternatives such as NVIDIA PhysX or Bullet, the former supporting GPU multi-threading. I'm not really sure if both supports CPU multi-threading.

However, single-threaded code for a physics engine is common in the game industry. 

IIRC some engines from e.g. Valve (Rubikon), Blizzard (Domino) all run in one thread. It seems when adding multi-threaded code the solution diverges from the elegant and simple solution we aim so much during development. So we care about other solutions such as improving cache performance, memory allocation speed, rather than spawing tons of threads for collision detection and simulation.

Does that answer the question?

**Comment by ForgeMistress** [comment]
Yeah, that answers it fairly well. My organization is actually looking at alternatives to Bullet because out simulations are starting to grow beyond what Bullet is feasibly capable of handling, hence why I checked your library out. So far PhysX and Chrono are my top contenders since their CPU simulation pipelines are already effectively multithreaded.

**Comment by irlanrobson** [comment]
Between Bullet and PhysX, my choice would be PhysX because it is much more consistent than Bullet. 

I haven't taken a look at Chrono yet.

**Comment by ForgeMistress** [comment]
Chrono is pretty nice, however there is a lot of library to unpack and a lot of settings that you can tweak that will cause your simulation to explode.

**Comment by irlanrobson** [comment]
I worked with PhysX for rigid bodies and cloth before. Their API design is pretty nice. Their code is also very optimized. That would be my option.
