### ISSUE TITLE
b3Body::ShouldCollide is not working for Static/Kinematic collisions

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#55]
`
bool b3Body::ShouldCollide(const b3Body* other) const
{
	if (m_type != e_dynamicBody && other->m_type != e_dynamicBody)
	{
		// At least one body should be kinematic or dynamic.
		return false;
...
The above code should be 
	if (m_type == e_staticBody && other->m_type == e_staticBody)
`

**Comment by irlanrobson** [comment]
At least one body should be dynamic. 

That if statement is correct. There's a typo in the comment above it though.

Kinematic bodies always have their transforms set through their velocities. They are commonly defined to follow an animation. The game is responsible for setting the velocities which will give the desired transforms. There can't be collision response between those objects and static objects. Otherwise their velocity wouldn't be constant. They don't have velocities determined by contact forces.

**Comment by fredUmlaut** [comment]
There will be no collision response between static/kinematic but Bounce should 
report Kinematic/Static contacts to the user, which currently doesn't happen.
With the modified if statement such contacts get reported (like in Physx and Bullet).

**Comment by irlanrobson** [comment]
What are you trying to accomplish? Can't you do what you need using sensors? Basically sensors are bodies which don't respond to collisions. They are reported to the contact callback.

**Comment by fredUmlaut** [comment]
Our games uses a kinematic body to push dynamic objects around. We need to know the contacts when the kinematic body touches dynamic bodies but also when it touches the static level geometry.
So i think a Sensor won't solve the problem because it can't push objects around.

**Comment by irlanrobson** [comment]
Do you need the actual contact manifolds between kinematic and static/kinematic bodies or just a persistent overlap notification?

**Comment by fredUmlaut** [comment]
An actual manifold would be what we need.

**Comment by irlanrobson** [comment]
Okay. Will see what I can do...

**Comment by fredUmlaut** [comment]
Thanks!

**Comment by irlanrobson** [comment]
Added this feature in a new commit. See if it works and post it back the results please.

**Comment by fredUmlaut** [comment]
Thanks a lot.
