### ISSUE TITLE
Bodies collide with mesh triangle edges 

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#56]

**Comment by fredUmlaut** [comment]
For instance, bodies that are moved over a subdivided plane mesh will get stuck on the meshs internal triangle edges.

Your YouTube video 'Smooth Mesh Contacts' refers to a solution. Is this currently working in Bounce?

**Comment by irlanrobson** [comment]
That video was recorded using an very earlier version of the library. You can even find some code if you browse the files. That code just handles sphere vs. mesh. Handling arbitrary shapes gets more involved and I don't have plans to implement this.

**Comment by fredUmlaut** [comment]
Do you mean the 'b3GJKShapeCastCSO' function?

Bullet used a prepass with the btInternalEdgeUtility. It was not perfect but allowed to use Bullet in typical game cases (for instance moving box crates on triangle mesh without getting stuck).

For one of our games with an own physics solution i worked around the issue by disregarding edge contacts when they were under a certain treshold. Given the simplicity of this approach it worked very well. Perhaps this would be an option for Bounce too?

**Comment by irlanrobson** [comment]
> Do you mean the 'b3GJKShapeCastCSO' function?

No. This is used for continuous collision.

> Bullet used a prepass with the btInternalEdgeUtility. It was not perfect but allowed to use Bullet in typical game cases (for instance moving box crates on triangle mesh without getting stuck).

IIRC Bullet doesn't tags the features a convex/concave/coplanar in a pre-processing step like PhysX does. It handles this in place. This is why is not perfect. 

> For one of our games with an own physics solution i worked around the issue by disregarding edge contacts when they were under a certain treshold. Given the simplicity of this approach it worked very well. Perhaps this would be an option for Bounce too?

When using GJK this can be trivial to implement since you can identify the closest features. I only implemented this for a sphere vs mesh, which worked correctly as in that video. 

However, I use SAT for convex vs. mesh. If I would do this again I would simple pass the features which I don't want to get selected as separating axis. There is more work involved, but I am not really into this topic at the moment. 

If you have implemented a general solution to this using SAT and GJK then I would be happy to know it.

**Comment by fredUmlaut** [comment]
Bullet computed connectivity info on demand in a preprocessing step. Then at runtime it used that info to filter out back facing triangles and to detect triangle edges. The edge detection used a precomputed edge distance threshold for each face. It was a bit rough, but worked.

> If you have implemented a general solution to this using SAT and GJK then I would be happy to 
> know it.

No sorry, my solution was only rejecting such edges reported from GJK, just like you describe above.

Perhaps b3RebuildEdgeContact could be used when looking at the barycentrics?

**Comment by irlanrobson** [comment]
> Perhaps b3RebuildEdgeContact could be used when looking at the barycentrics?

Nah, that's just a cached version of b3BuildEdgeContact.

**Comment by fredUmlaut** [comment]
> You can even find some code if you browse the files. That code just handles sphere vs. mesh. 

Could you point me to the source file? At least i doesn't seem to get used for sphere/mesh. There GJK is used currently.

**Comment by irlanrobson** [comment]
> Could you point me to the source file? At least i doesn't seem to get used for sphere/mesh. There GJK is used currently.

Yeah. It's here:

https://github.com/irlanrobson/bounce/blob/20e06be722ee05fcf97a0b415a9b47786c5a8338/src/bounce/dynamics/contacts/collide/collide_sphere_mesh.cpp

The code above is an implementation for the algorithm described in this publication by Pierre:

http://www.codercorner.com/MeshContacts.pdf

**Comment by fredUmlaut** [comment]
That paper has a good solution. An important point when implementing that algorithm is not to use the naive case of a single mesh (which is also discussed at the end of the paper) .
The algorithm need to take ALL contacts between multiple meshes into account, otherwise there will still be wrong collisions when a body moves from one mesh to another.

**Comment by irlanrobson** [comment]
Mesh contacts is an open problem.

Bounce just generates one contact manifold per triangle and sends them for clustering, sending them to the contact solver.

**Comment by irlanrobson** [comment]
I added some code to skip unwanted edge contacts. However, it only works for meshes against hulls. 

The good thing is that the algorithm I implemented is exact. It is also extremelly fast.

The only external change is that from now on users will have to call the following function for marking up the mesh features before using the mesh:

b3Mesh::ComputeEdgeTypes();

This function can take a while to run! I am willing to perform both space and time optimization of this function, and maybe the entire pre-processing step.

It might take a while until I implement this feature for all shape combinations.

I would be very happy if you could test this feature and post back some results when possible because I tested this only with a box on meshes. It is working fine as far as I tested.

**Comment by fredUmlaut** [comment]
Sounds great Irlan! 

> However, it only works for meshes against hulls.
So this means if a body moves over a single mesh it should discard such edges, but if the body moves from one mesh to another it could get stuck, right? .. I just want to be sure for testing ..
I will test as soon as possible and give you feedback!

**Comment by irlanrobson** [comment]
The algorithm works first by tagging the mesh edges as isolated, convex, concave, or coplanar. In this step is where I have to find all adjacent triangles and the corresponding shared edges. This is why this step is slow.

Currently the coplanarity tolerance is defined internally depending of the mesh size. I will probably allow the users to scale this value in the future through a macro. It is important to let users take control of this value.

I only skip contacts against *coplanar* edges. Skipping against concave edge can push a body out of the world in some cases.

Then if a coplanar edge is chosen to be the contact point I create a triangle face contact for getting good normals. 

I don't clamp/average/interpolate the normals or anything like this because that's a hack.

**Comment by irlanrobson** [comment]
> So this means if a body moves over a single mesh it should discard such edges, but if the body moves from one mesh to another it could get stuck, right?

Yes, that is true! 

For example, if you are making a racing game and then one part of a lane is a mesh and the adjacent lane is another mesh then a hull can get bumped into a shared boundary edge. 

Here I would probably try to explicitly tag those boundary edges from isolated to coplanar so they are skipped too!

**Comment by fredUmlaut** [comment]
I understand. In a racing game you may have such information at hand, but in other games it will be very hard for most users to get such information.

Perhaps it would be possible to build first a cache for the shared edges that a body may touch each frame? Then such edges could be filtered out.
Another solution would be to process all meshes the body touches like a single mesh. 
What do you think?

**Comment by irlanrobson** [comment]
After some refactoring now you will have to call b3Mesh::BuildEdges for tagging the mesh edges.

The following macro has been added to settings.h:

B3_MESH_COPLANARITY_SCALE

The coplanarity tolerance (epsilon) is proportional to this value. The defaults scale is 1. You can increase this value as you want.

As for non-manifold meshes: Hulls rarely collide against the shared edges of those in shallow penetration, so I think overwriting the edge type is fine, which is what I do right now. I'll test this in the future to see if I should handle this case in a more rational way. However, try to avoid manifold meshes when possible. As I said earlier mesh contacts is a kind of an open problem and there is no definite solution to this.

**Comment by fredUmlaut** [comment]
I tested 'mesh->ComputeEdgeTypes' and first impression was very good!!
I will give it more testing for different cases...

There seems now to be an issue in 'b3MeshContact::Collide()' when 
mesh->ComputeEdgeTypes() is NOT called. 
Null pointer access because meshB->triangleEdges ==0

**Comment by irlanrobson** [comment]
Yeah, I renamed ComputeEdgeTypes to BuildEdges!

**Comment by irlanrobson** [comment]
Sorry for the refactoring! Anything for making the API more user friendly!

**Comment by irlanrobson** [comment]
One more modification: 

Pass the coplanarity scale as a parameter to b3Mesh::BuildEdges. You might want to chose a different scale per mesh.

**Comment by irlanrobson** [comment]
> Perhaps it would be possible to build first a cache for the shared edges that a body may touch each frame? Then such edges could be filtered out.
> Another solution would be to process all meshes the body touches like a single mesh.
> What do you think?

If merging the adjacent triangle meshes (1) (that is, welding the coincident edge vertices) is not an option for you then tagging the shared boundary edges as coplanar can work. Users already have write access to the unique mesh edges. 

You can find a good test to classify an edge at the end of mesh.cpp.

**Comment by fredUmlaut** [comment]
A general solution (which would also work for kínematic/dynamic bodies) would be to classify in BuildEdges() the edges of the end of an mesh and store them with startpos/endpos and normal.

When then contacts are generated between hulls and meshes, such marked edges should be stored as references in the contact.

Then it could be iterated over all contacts of a body to see if there are nearly coplanar edges. 
If yes, then both contacts could be safely discarded before they get solved.
What do you think?

**Comment by irlanrobson** [comment]
What you're saying sounds more like a run-time solution to the problem. If your game has dynamic game levels then what you said could possibly be one way to approach the problem.

In my opinion you should cook that out because rarely you need to create those kinds of adjacent meshes at run-time. Game designers use meshes mostly for defining static game levels. Everything else is spheres, capsules and hulls. So try to bake out as many things you can!

> When then contacts are generated between hulls and meshes, such marked edges should be stored as references in the contact.

For the static case I would put the extra shared edges into b3MeshShape.

**Comment by fredUmlaut** [comment]
Yes, i mean a general run-time algorithm as its the only solution for many type of games.

Its excellent that bounce already supports mesh instancing. Game worlds are often quite big, often too big to get baked easily. You have 1000s of large instanced physics meshes (or even much more). It takes a lot of space and time to bake them. Also a static solution blocks certain game types which rely on dynamic creation of levels elements.

**Comment by irlanrobson** [comment]
I've just added coplanar edge filtering for spheres and capsules as well.

**Comment by irlanrobson** [comment]
Hi there! 

I've implemented several algorithms for reducing the problem of collisions between shapes and the internal edges of a manifold mesh. They also handle convex edges.

For the algorithms to work the function b3Mesh::BuildAdjacency() must be called before using a mesh as a shape mesh. This will not work if your mesh has edges shared across more than two triangles. The code won't connect the edges properly. Probably in the future it won't work if there are non-manifold vertices too. 

Also, there is no vertex adjacency yet, so there can be collisions with the internal vertices of the mesh. Fortunately this occurs unfrequently if your mesh is not a dense mesh.

Again, this is a difficult problem and it can be very difficult to solve this problem exactly without constraining the mesh structure.

I also added a triangle shape. It might be helpfull for creating small meshes as it does not require you to build a tree. This shape allows you to provide edge adjacency. Each edge can be shared with exactly two faces. You must provide the wing vertex of the adjacent face of an edge and a flag to tell the wing vertex exists. 

The following image illustrates a triangle whose edges are connected to exactly one adjacent triangle. The red points are the wing vertex of each edge.

![wing](https://user-images.githubusercontent.com/4203641/66273929-489fbf80-e84f-11e9-8c80-5d3462cb193c.png)

If you seem to have problems with your mesh I recommend performing mesh simplification to improve the quality of your mesh. I haven't tested it yet but this seems to be a good QEM simplificator:

https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification

This kind of simplificator is commonly used in the game industry. 

Another is voxelize and remesh.

**Comment by fredUmlaut** [comment]
Sounds really good Irlan. Thanks for all these great improvements.
I will test this out asap!

> This will not work if your mesh has edges shared across more than two triangles.

I don't think this is an issue. This should not happen with sane meshes.
