### ISSUE TITLE
How do I create a shape?

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#6]
Hi, sorry for using the issue tracker for a support question. I'm just trying to swap out qu3e with bounce in my game engine and I'm having trouble generating a box collider. Here's the code I'm using:

```
            b3BoxHull def;
            def.Set(aabb.width(), aabb.height(), aabb.depth());

            b3HullShape hsdef;
            hsdef.m_hull = &def;

            b3ShapeDef sdef;
            sdef.density = 1.0;
            sdef.shape = &hsdef;
            sdef.userData = this;

            sim->bodies_.at(this)->CreateShape(sdef);
```

This seems to fail with some kind of corruption, the next time I interact with the body the `m_hull` variable is full of junk data. Do you know what I'm doing wrong? Thanks!

**Comment by irlanrobson** [comment]
You're creating a temporary b3BoxHull object. A b3BoxHull object is a shared resource, so it can be reused. Whereas a b3HullShape isn't.  You can attach a b3BoxHull object to many b3HullShape objects, so you can use the same geometry but with different physics parameters such as density, friction, and restitution.

**Comment by Kazade** [comment]
Ah! Ok thanks that explains it! Cheers for the excellent library :)

**Comment by irlanrobson** [comment]
The same applies to a b3Mesh object. You can reuse it to create many b3MeshShape objects  you need. 

However, the same doesn't apply to a b3SphereShape and a b3CapsuleShape because these are just primitives. To create a sphere, for example, you would write:

b3SphereShape sphere;
sphere.m_center.Set(0.0f, 0.0f, 0.0f);  
sphere.m_radius = 1.0f;

b3ShapeDef def;
def.density = 1.0f;
def.shape = &sphere;

body->CreateShape(def);

The same for capsules.

**Comment by irlanrobson** [comment]
Also, it's important to note that **a shape is defined in the space of the rigid body that owns it**.

**Comment by irlanrobson** [comment]
I recommend seeing the Multiple Shapes test in the testbed. It shows how to attach multiple boxes located at different positions in the space of their parent body. Bounce doesn't support compound shapes since here the shapes are very simple and do not consume much memory. 

For example, if you need to create a body and add three boxes to it located at three different positions from the body origin (which is usually expected) you need to create three b3BoxHull objects and shift them appropriately.

**Comment by Kazade** [comment]
Thanks for all that information, really appreciate it!

So I have everything working except for one thing. No matter what I try, `ApplyTorque` doesn't seem to do anything. It certainly sets m_torque, but I'm not seeing any rotation.

Any ideas?

**Comment by Kazade** [comment]
Ignore, I hadn't set a density :)
