### ISSUE TITLE
b3HullShape supports no scale

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#73]
Similar to b3MeshShape it would save a lot of vertex duplication, if b3HullShape 
would have a 'b3Vec3 m_scale' property.

**Comment by irlanrobson** [comment]
Hulls are most of the time simplified and very small. I don't think this will make such a huge difference.

It also adds some complexity. Anyways, I'll take this into consideration for future versions...

**Comment by fredUmlaut** [comment]
You, are right. And its certainly not as bad as with triangle meshes.

Such scaling helps in situations where you create shapes with convex hulls in realtime and each of them has a different scale. So there are peaks when creating these bodies due to the extra scaling step and the quickhull generation...    In Bullet i cached the Quickhull and used scaling. But its not a big problem currently for me currently.. so don't worry :)

**Comment by irlanrobson** [comment]
For creating a convex hull from a set of points see b3QHull::Set(...) inside the collision module. 

The Q here stands for "quick". I use this in some of constant resources for user convenience. There is a flag that can be passed to this function called `simplify` which allows you to simplify the initial convex hull. 

Bear in mind that calling this function can be slow because it performs simplification in dual space. So if you set this flag to true three convex hulls will be created inside this function. This means three calls to quickhull!

The first hull is the initial (non-simplified) convex hull. 

The second is the convex hull in dual space. In this space I can perform simplification using some kind of algorithm such as duplicated face removal (e.g. up to 45 degrees, currently implemented) or even a more advanced clustering algorithm such as k-means. 

The third hull is the recovered convex hull from dual space to primary space.

So calling quickhull at real-time is fine. Simplifying a hull in real-time can be slow. However, we can optimize memory allocation.

**Comment by irlanrobson** [comment]
I can add a function inside b3Hull which takes a translation/scale/rotation as parameters and performs the corresponding transformation. This way you call Quickhull just once and just transform the reference hull using those functions. This should be sufficient.

**Comment by irlanrobson** [comment]
But note copying b3Hull objects should be your responsibility. Adding copying operators to constant resources since can increase complexity pretty easely. This should be easy to add though.

When I first wrote I assumed b3Hull objects were baked out. This is why I don't put copying operators inside those for simplicity/clarity.

**Comment by fredUmlaut** [comment]
The user usually needs the same hull, but with different transform and different scales. So i would not bother with baking these. Instead it would be nice to have a scale property for b3Hull, which would avoid data duplication for most common cases.

If the user wants to bake anything he should do this on his own. I don't think b3Hull needs that functionality. Tho, such baking would not be needed when a scale param would be available.

**Comment by irlanrobson** [comment]
This feature would make code involving hulls prettty. It involves too much transformation... vertices and planes all around.

The user should be fine with transforming the vertices and building the hull. This is fast.

We target a maximum of 10-15 vertices per hull for performance reasons.

**Comment by fredUmlaut** [comment]
I see, especially with planes this gets messy..  would be interesting to see how bullet/physx handle that..

**Comment by irlanrobson** [comment]
IIRC Bullet uses GJK and EPA. For those algorithms to work it is sufficient the hulls are defined as a collection of points. It doesn't require plane neither a mesh structure with adjacency information.

Bounce uses SAT and generates one-shot contact manifolds. That is numerically a better choice over GJK and EPA. It also gives more stable manifolds. For this to work fast it requires we define hulls using a polygon mesh structure containing adjacency information and also a set of planes.

**Comment by fredUmlaut** [comment]
Yes, GJK/EPA are the default, but Bullet also supports SAT. I quickly scanned through the source and when using SAT it seems not to look at all at scaling. Would need testing, but it seems as its not working with SAT.
