### ISSUE TITLE
Is a C library possible?

### ISSUE THREAD

**Issue by orange451** [irlanrobson/bounce#98]
Just curious. Makes it easier to integrate with LWJGL. Could open this up to being used by a lot of users. If not don't worry :)

**Comment by irlanrobson** [comment]
It is possible to port it to C and it may not be a difficult task. However, I am not doing this because I use inheritance quite a bit for quickly abstracting code. If I switch to C I may lose some iteration time I guess.

However, not all C++ features are obeyed in this library. Because a feature exists, it doesn't mean one should use it. Neither I wrap every operation in a class. You can see here lots of free functions preferred over objects. The lower level my code becomes, the more gets closer to pure C.
